# Checks for drift between train & prod data, and
# retrains the model when drift is detected
name: Data Drift Check

on:
  # FIXME: We would typically run this every day, but since this is just an example
  # we will instead emulate executions by running POST requests directly from a script
  # schedule:
  #   - cron: '0 0 * * *'  # Run every day at midnight
  push: # run on push to debugging branch
    branches: e2e_mock  # Run on push to e2e_mock branch
  repository_dispatch:  # Allows webhook triggering
    types: [new_prod_data_batch]

jobs:
  drift_check:
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v2

      - name: 🐍 Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install pipenv
          cd drift
          pipenv sync

      - name: ⚙️ Run Drift Check
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          cd drift
          pipenv run python check_drift.py
  retrain:
    needs: drift_check
    runs-on: self-hosted
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v2

      - name: ⚙️ Train!
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python train.py
