# Checks for drift between train & prod data, and
# retrains the model when drift is detected
name: Data Drift Check

on:
  workflow_run: # Trigger after another workflow completes
    workflows: [Production Data Batching]
    types:
      - completed

jobs:
  drift_check:
    runs-on: ubuntu-latest
    outputs:  # Define outputs for downstream jobs
      drift_detected: ${{ steps.drift_check.outputs.drift_detected }}
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install pipenv
          cd drift
          pipenv sync

      - name: ⚙️ Run Drift Check
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        id: drift_check
        run: |
          cd drift
          output=$(pipenv run python check_drift.py)
          echo "$output"
          drift_detected=$(echo "$output" | grep "DRIFT_DETECTED=" | cut -d'=' -f2)
          echo "drift_detected=$drift_detected" >> $GITHUB_OUTPUT

  retrain:
    needs: drift_check
    if: ${{ needs.drift_check.outputs.drift_detected == 'True' }}
    runs-on: self-hosted
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Train!
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python train.py
