name: Data Drift Check

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Run every day at midnight
  repository_dispatch:  # Allows webhook triggering
    types: [new_prod_data_batch]

jobs:
  drift_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          cd drift
          pip install -r requirements.txt

      - name: Run Drift Check
        run: |
          cd drift
          python check_drift.py
