# Checks model performance, and retrains
# if model degradation is detected
name: Performance Evaluation

on:
  workflow_run: # Trigger after another workflow completes
    workflows: ["Production Data Batching"]
    types:
      - completed
  push:
    branches: ijdoc/issue9

jobs:
  eval_check:
    runs-on: ubuntu-latest
    outputs:  # Define outputs for downstream jobs
      drift_detected: ${{ steps.eval_check.outputs.degraded }}
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install pipenv
          cd eval
          pipenv sync

      - name: ⚙️ Run Evaluation
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        id: eval_check
        run: |
          cd drift
          output=$(pipenv run python eval.py)
          echo "$output" >> $GITHUB_STEP_SUMMARY

  # Uncomment the following block to automatically
  # retrain the model when drift is detected
  # retrain:
  #   needs: eval_check
  #   if: ${{ needs.eval_check.outputs.drift_detected == 'True' }}
  #   runs-on: self-hosted
  #   steps:
  #     - name: ⏬ Checkout repository
  #       uses: actions/checkout@v4

  #     - name: ⚙️ Train!
  #       env:
  #         WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
  #       run: |
  #         python train.py
